version: '3'
services:
  andes:
    image: obitech/andes-api:0.2.1
    expose:
      - "5000"
      - "5001"
    volumes:
      - "./system/api/data:/andes/api/data"
      - "./stacks:/andes/stacks"
    networks:
      andes_default:
        ipv4_address: 172.42.0.2
    restart: always
  web:
    cap_add:
      - NET_ADMIN
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./system/Caddyfile:/etc/Caddyfile"
      - "./system/certs:/root/.caddy"
      - "./system/vhosts:/etc/caddy/sites-enabled"
      - "./system/frontend:/srv/www"
    links:
      - andes
    networks:
      andes_default:
        ipv4_address: 172.42.0.3
    restart: always
networks:
  andes_default:
    external: true
