site_name: Andes API documentation
site_description: "Andes API Documentation"
site_url: https://obitech.github.io/andes/
site_author: "obitech"

repo_url: https://github.com/obitech/andes
repo_name: 'GitHub'
edit_uri: ""

pages:
  - Home: 'index.md'
  - Endpoint Reference: 
    - 'Authentication':
      - '/register':
        - 'POST': 'endpoints/user/register/post.md'
      - '/auth': 
        - 'POST': 'endpoints/user/auth/post.md'
    - 'Blueprints':
      - '/blueprints': 
        - 'GET': 'endpoints/blueprints/get.md'
      - '/blueprints/<_id>':
        - 'GET': 'endpoints/blueprints/id/get.md'
        - 'DELETE': 'endpoints/blueprints/id/delete.md'
      - '/blueprints/create':
        - 'POST': 'endpoints/blueprints/create/post.md'
        - 'PUT': 'endpoints/blueprints/create/put.md'
    - 'Services':
      - '/services':
        - 'GET': 'endpoints/services/get.md'
      - '/services/<_id>':
        - 'GET': 'endpoints/services/id/get.md'
        - 'DELETE': 'endpoints/services/id/delete.md'
      - '/services/create':
        - 'POST': 'endpoints/services/create/post.md'
        - 'PUT': 'endpoints/services/create/put.md'
    - 'Stacks':
      - '/stacks':
        - 'GET': 'endpoints/stacks/get.md'
      - '/stacks/<_id>':
        - 'GET': 'endpoints/stacks/id/get.md'
        - 'DELETE': 'endpoints/stacks/id/delete.md'
      - '/stacks/create':
        - 'POST': 'endpoints/stacks/create/post.md'
        - 'PUT': 'endpoints/stacks/create/put.md'
      - '/stacks/<_id>/apply':
        - 'POST': 'endpoints/stacks/id/apply/post.md'
